# ═══════════════════════════════════════════════════════════════
#  D-PlaneOS v2.0.0 — NixOS Configuration (Standalone)
# ═══════════════════════════════════════════════════════════════
#
#  Use this if you don't want to use Flakes.
#  For the Flake version, use configuration.nix + flake.nix instead.
#
#  Installation:
#    1. sudo cp configuration-standalone.nix /etc/nixos/configuration.nix
#    2. sudo bash setup-nixos.sh
#    3. sudo nixos-rebuild switch
#    4. Open browser → http://<server-ip>
#
#  Broken? → sudo nixos-rebuild switch --rollback
#
# ═══════════════════════════════════════════════════════════════

{ config, pkgs, lib, ... }:

let

  # ┌─────────────────────────────────────────────────────────┐
  # │  CHANGE HERE (1/5): Your ZFS pool name                  │
  # │                                                         │
  # │  Examples: "tank", "datapool", "nas"                    │
  # └─────────────────────────────────────────────────────────┘
  zpools = [ "tank" ];

  # Samba workgroup (default "WORKGROUP" is fine for most setups)
  sambaWorkgroup = "WORKGROUP";

  # ─── D-PLANEOS PACKAGES (do not modify) ──────────────────

  # Go daemon (dplaned)
  dplaned = pkgs.buildGoModule rec {
    pname = "dplaned";
    version = "2.0.0";

    src = pkgs.fetchFromGitHub {
      owner = "4nonX";
      repo = "dplaneos";
      rev = "v${version}";
      # Get this hash with:
      #   nix-shell -p nix-prefetch-github --run "nix-prefetch-github 4nonX dplaneos --rev v2.0.0"
      hash = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
    };

    sourceRoot = "${src.name}/daemon";

    # Get this hash automatically: set to "" (empty string),
    # then "nixos-rebuild switch" will show the correct hash in the error message.
    vendorHash = "";

    CGO_ENABLED = 1;
    buildInputs = [ pkgs.sqlite ];

    meta = with lib; {
      description = "D-PlaneOS NAS System Daemon";
      homepage = "https://github.com/4nonX/dplaneos";
      license = licenses.mit;
    };
  };

  # Frontend (static website)
  dplaneos-frontend = pkgs.stdenv.mkDerivation rec {
    pname = "dplaneos-frontend";
    version = "2.0.0";

    src = pkgs.fetchFromGitHub {
      owner = "4nonX";
      repo = "dplaneos";
      rev = "v${version}";
      # Same hash as above:
      hash = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
    };

    installPhase = ''
      mkdir -p $out
      cp -r app/* $out/
    '';
  };

  # Recovery tool for password reset etc.
  dplaneos-recovery = pkgs.writeShellScriptBin "dplaneos-recovery" ''
    DB="/var/lib/dplaneos/dplaneos.db"
    echo "D-PlaneOS Recovery CLI v2.0.0"
    echo ""
    echo "1) Reset admin password"
    echo "2) Show system status"
    echo "3) Create database backup"
    echo "4) Exit"
    read -p "Choice: " choice
    case $choice in
      1)
        read -sp "New admin password: " pw; echo
        HASH=$(${pkgs.apacheHttpd}/bin/htpasswd -nbBC 10 "" "$pw" | cut -d: -f2)
        ${pkgs.sqlite}/bin/sqlite3 "$DB" "UPDATE users SET password_hash='$HASH' WHERE username='admin';"
        echo "Admin password reset."
        ;;
      2)
        echo "Database: $(du -h $DB)"
        echo "Sessions: $(${pkgs.sqlite}/bin/sqlite3 "$DB" "SELECT COUNT(*) FROM sessions;")"
        echo "Users: $(${pkgs.sqlite}/bin/sqlite3 "$DB" "SELECT COUNT(*) FROM users;")"
        ;;
      3)
        BACKUP="/var/lib/dplaneos/backups/dplaneos-$(date +%Y%m%d-%H%M%S).db"
        ${pkgs.sqlite}/bin/sqlite3 "$DB" ".backup $BACKUP"
        echo "Backup saved: $BACKUP"
        ;;
      *) echo "Bye." ;;
    esac
  '';

in {

  # Hardware detection (auto-generated by NixOS — DO NOT delete!)
  imports = [
    ./hardware-configuration.nix
  ];

  # ═══════════════════════════════════════════════════════════
  #  SYSTEM
  # ═══════════════════════════════════════════════════════════

  system.stateVersion = "24.11";

  networking.hostName = "dplaneos";

  # ┌─────────────────────────────────────────────────────────┐
  # │  CHANGE HERE (2/5): ZFS host ID                          │
  # │                                                         │
  # │  Generate one with:                                     │
  # │    head -c4 /dev/urandom | od -A none -t x4 | tr -d ' '│
  # │  Or let setup-nixos.sh handle it automatically.         │
  # └─────────────────────────────────────────────────────────┘
  networking.hostId = "CHANGE_ME";

  # ┌─────────────────────────────────────────────────────────┐
  # │  CHANGE HERE (3/5): Timezone                             │
  # └─────────────────────────────────────────────────────────┘
  time.timeZone = "Europe/Berlin";

  i18n.defaultLocale = "en_US.UTF-8";

  # ═══════════════════════════════════════════════════════════
  #  BOOTLOADER
  # ═══════════════════════════════════════════════════════════

  # ┌─────────────────────────────────────────────────────────┐
  # │  CHANGE HERE (4/5): Boot loader                          │
  # │                                                         │
  # │  Option A: UEFI (default, most PCs since ~2012)         │
  # │  Option B: Legacy BIOS → comment out A, uncomment B     │
  # └─────────────────────────────────────────────────────────┘

  # Option A: UEFI
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Option B: Legacy BIOS/MBR
  # boot.loader.grub.enable = true;
  # boot.loader.grub.device = "/dev/sda";

  # ═══════════════════════════════════════════════════════════
  #  ZFS
  # ═══════════════════════════════════════════════════════════

  boot.supportedFilesystems = [ "zfs" ];
  boot.zfs.forceImportRoot = false;
  boot.zfs.extraPools = zpools;

  services.zfs.autoScrub = {
    enable = true;
    interval = "monthly";
  };

  services.zfs.autoSnapshot = {
    enable = true;
    frequent = 4;    # Every 15 min, keep 4
    hourly = 24;
    daily = 7;
    weekly = 4;
    monthly = 12;
  };

  # ZFS ARC (read cache)
  #   16 GB RAM → 8589934592  (8 GB)
  #   32 GB RAM → 17179869184 (16 GB)  ← current
  #   64 GB RAM → 34359738368 (32 GB)
  boot.kernelParams = [
    "zfs.zfs_arc_max=17179869184"
  ];

  # ═══════════════════════════════════════════════════════════
  #  KERNEL TUNING (optimized for NAS — do not modify)
  # ═══════════════════════════════════════════════════════════

  boot.kernel.sysctl = {
    "fs.inotify.max_user_watches" = 524288;
    "fs.inotify.max_user_instances" = 512;
    "vm.swappiness" = 10;
    "vm.vfs_cache_pressure" = 50;
    "net.core.rmem_max" = 16777216;
    "net.core.wmem_max" = 16777216;
  };

  # ═══════════════════════════════════════════════════════════
  #  NGINX (web server for D-PlaneOS UI)
  # ═══════════════════════════════════════════════════════════

  services.nginx = {
    enable = true;
    recommendedGzipSettings = true;
    recommendedOptimisation = true;
    recommendedProxySettings = true;

    virtualHosts."dplaneos" = {
      default = true;
      root = "${dplaneos-frontend}";

      extraConfig = ''
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Referrer-Policy "no-referrer-when-downgrade" always;
      '';

      locations = {
        "~* \\.(css|js|jpg|jpeg|png|gif|ico|svg|woff|woff2|ttf|eot)$" = {
          extraConfig = "access_log off; expires 30d; add_header Cache-Control \"public, immutable\";";
        };
        "/" = { tryFiles = "$uri $uri/ /pages/index.html"; };
        "/api/" = {
          proxyPass = "http://127.0.0.1:9000";
          proxyWebsockets = false;
          extraConfig = "proxy_read_timeout 120s; proxy_connect_timeout 10s;";
        };
        "/ws/" = {
          proxyPass = "http://127.0.0.1:9000";
          proxyWebsockets = true;
          extraConfig = "proxy_read_timeout 86400s;";
        };
        "/health" = { proxyPass = "http://127.0.0.1:9000/health"; };
        "~ \\.php$" = { extraConfig = "deny all;"; };
        "~ /\\." = { extraConfig = "deny all;"; };
        "~ /(config|daemon|scripts|systemd)/" = { extraConfig = "deny all;"; };
      };
    };
  };

  # ═══════════════════════════════════════════════════════════
  #  D-PLANEOS DAEMON (do not modify)
  # ═══════════════════════════════════════════════════════════

  systemd.services.dplaned = {
    description = "D-PlaneOS System Daemon";
    after = [ "network.target" "zfs-import.target" "zfs-mount.service" ];
    wants = [ "zfs-import.target" ];
    requires = [ "zfs-mount.service" ];
    wantedBy = [ "multi-user.target" ];

    serviceConfig = {
      Type = "simple";
      ExecStart = lib.concatStringsSep " " [
        "${dplaned}/bin/dplaned"
        "-db /var/lib/dplaneos/dplaneos.db"
        "-listen 127.0.0.1:9000"
        "-config-dir /var/lib/dplaneos/config"
        "-smb-conf /var/lib/dplaneos/smb-shares.conf"
      ];
      WorkingDirectory = "/var/lib/dplaneos";
      Restart = "always";
      RestartSec = 5;
      User = "root";
      Group = "root";
      RuntimeDirectory = "dplaneos";
      RuntimeDirectoryMode = "0755";
      StateDirectory = "dplaneos";
      LogsDirectory = "dplaneos";
      NoNewPrivileges = true;
      PrivateTmp = true;
      ProtectSystem = "strict";
      ProtectHome = true;
      ReadWritePaths = [ "/var/log/dplaneos" "/var/lib/dplaneos" "/run/dplaneos" ];
      AmbientCapabilities = [ "CAP_SYS_ADMIN" "CAP_NET_ADMIN" "CAP_DAC_READ_SEARCH" "CAP_CHOWN" "CAP_FOWNER" ];
      LimitNOFILE = 65536;
      TasksMax = 4096;
      MemoryMax = "1G";
      MemoryHigh = "768M";
      OOMScoreAdjust = -900;
    };
  };

  systemd.tmpfiles.rules = [
    "d /var/lib/dplaneos 0750 root root -"
    "d /var/lib/dplaneos/backups 0750 root root -"
    "d /var/lib/dplaneos/config 0750 root root -"
    "d /var/lib/dplaneos/config/ssl 0700 root root -"
    "f /var/lib/dplaneos/smb-shares.conf 0644 root root -"
  ];

  # ═══════════════════════════════════════════════════════════
  #  SAMBA (Windows file sharing)
  # ═══════════════════════════════════════════════════════════

  services.samba = {
    enable = true;
    openFirewall = true;

    settings.global = {
      workgroup = sambaWorkgroup;
      "server string" = "D-PlaneOS NAS";
      security = "user";
      "map to guest" = "Bad User";
      "log file" = "/var/log/samba/log.%m";
      "max log size" = "1000";
      "socket options" = "TCP_NODELAY IPTOS_LOWDELAY SO_RCVBUF=131072 SO_SNDBUF=131072";
      "read raw" = "yes";
      "write raw" = "yes";
      "use sendfile" = "yes";
      "aio read size" = "16384";
      "aio write size" = "16384";
    };

    extraConfig = "include = /var/lib/dplaneos/smb-shares.conf";
  };

  # ═══════════════════════════════════════════════════════════
  #  NFS + DOCKER
  # ═══════════════════════════════════════════════════════════

  services.nfs.server.enable = true;

  virtualisation.docker = {
    enable = true;
    storageDriver = "zfs";
    autoPrune = { enable = true; dates = "weekly"; };
    daemon.settings = {
      "log-driver" = "json-file";
      "log-opts" = { "max-size" = "10m"; "max-file" = "3"; };
      "default-address-pools" = [ { base = "172.17.0.0/16"; size = 24; } ];
    };
  };

  # ═══════════════════════════════════════════════════════════
  #  NETWORKING + FIREWALL
  # ═══════════════════════════════════════════════════════════

  networking.firewall = {
    enable = true;
    allowedTCPPorts = [ 80 443 445 2049 ];
    allowedUDPPorts = [ 5353 ];
  };

  services.avahi = {
    enable = true;
    nssmdns4 = true;
    publish = { enable = true; addresses = true; workstation = true; };
  };

  # ═══════════════════════════════════════════════════════════
  #  MONITORING + TOOLS
  # ═══════════════════════════════════════════════════════════

  services.smartd = {
    enable = true;
    autodetect = true;
    notifications.wall.enable = true;
  };

  environment.systemPackages = with pkgs; [
    dplaned dplaneos-recovery
    zfs smartmontools hdparm lsof
    ethtool iperf3
    htop tmux git sqlite docker-compose
    nano
  ];

  # ═══════════════════════════════════════════════════════════
  #  SSH + USERS
  # ═══════════════════════════════════════════════════════════

  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "yes";
      PasswordAuthentication = true;
    };
  };

  # ┌─────────────────────────────────────────────────────────┐
  # │  CHANGE HERE (5/5): Admin user                           │
  # │  Set password after install: sudo passwd admin           │
  # └─────────────────────────────────────────────────────────┘
  users.users.admin = {
    isNormalUser = true;
    extraGroups = [ "wheel" "docker" ];
  };

  security.sudo.wheelNeedsPassword = true;

  # ═══════════════════════════════════════════════════════════
  #  SCHEDULED TASKS
  # ═══════════════════════════════════════════════════════════

  services.cron = {
    enable = true;
    systemCronJobs = [
      # Database backup daily at 3 AM, 30-day retention
      "0 3 * * *  root  ${pkgs.sqlite}/bin/sqlite3 /var/lib/dplaneos/dplaneos.db \".backup /var/lib/dplaneos/backups/dplaneos-$(date +\\%Y\\%m\\%d).db\" && find /var/lib/dplaneos/backups -mtime +30 -delete"
    ];
  };
}
