# D-PlaneOS v3.0.0 — NixOS Standalone Configuration
# ─────────────────────────────────────────────────────────────────────────────
# This file IS your entire NAS operating system configuration.
# Edit it, then run: sudo nixos-rebuild switch
#
# Getting started: see INSTALLATION-GUIDE-NIXOS.md
# ─────────────────────────────────────────────────────────────────────────────

{ config, lib, pkgs, ... }:

{
  imports = [
    # Auto-generated hardware config — do NOT edit this file manually.
    # Regenerate with: nixos-generate-config --root /mnt
    ./hardware-configuration.nix
  ];

  # ─── Allow D-PlaneOS (PolyForm Shield license) ──────────────────────────
  # NixOS classifies non-OSI-approved licenses as "unfree".
  # PolyForm Shield 1.0.0 is source-available but restricts commercial
  # competition — it is not OSI-approved, so this flag is required.
  #
  # This only permits the D-PlaneOS daemon specifically.
  # It does NOT globally enable all unfree packages.
  nixpkgs.config.allowUnfreePredicate = pkg:
    builtins.elem (lib.getName pkg) [
      "dplaneos-daemon"
    ];

  # ─── Boot loader ────────────────────────────────────────────────────────
  # UEFI (most systems since 2012) — use this block:
  boot.loader.systemd-boot.enable      = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Legacy BIOS/MBR — comment out the two lines above, uncomment these:
  # boot.loader.grub.enable  = true;
  # boot.loader.grub.device  = "/dev/sda";  # your boot disk

  # ─── ZFS ────────────────────────────────────────────────────────────────
  boot.supportedFilesystems = [ "zfs" ];

  # hostId MUST be unique per machine. setup-nixos.sh generates this.
  # Generate manually: head -c 8 /etc/machine-id
  networking.hostId = "00000000";  # ← setup-nixos.sh replaces this

  # ─── Networking ─────────────────────────────────────────────────────────
  networking.hostName = "dplaneos";

  # Use networkd (more reliable for NAS workloads than NetworkManager).
  networking.useDHCP         = false;
  networking.useNetworkd     = true;
  systemd.network.enable     = true;

  # Auto-configure the primary ethernet interface via DHCP.
  # Replace "eth0" with your actual interface name (ip link show).
  systemd.network.networks."10-eth0" = {
    matchConfig.Name = "eth0";
    networkConfig.DHCP = "yes";
  };

  # mDNS — allows access via http://dplaneos.local
  services.avahi = {
    enable   = true;
    nssmdns4 = true;
    publish  = {
      enable      = true;
      addresses   = true;
      workstation = true;
    };
  };

  # ─── Timezone & locale ──────────────────────────────────────────────────
  # setup-nixos.sh sets this. Change manually if needed.
  # Full list: timedatectl list-timezones
  time.timeZone = "Europe/Berlin";  # ← setup-nixos.sh replaces this

  i18n.defaultLocale = "en_US.UTF-8";

  # ─── Users ──────────────────────────────────────────────────────────────
  # The D-PlaneOS web UI manages users. This is just the system root.
  users.users.root = {
    initialHashedPassword = "";  # set during nixos-install
  };

  # ─── D-PlaneOS service ──────────────────────────────────────────────────
  services.dplaneos = {
    enable       = true;
    openFirewall = true;
    # listenAddress and listenPort use defaults (127.0.0.1:9000)
  };

  # ─── NTP ────────────────────────────────────────────────────────────────
  services.timesyncd.enable = true;

  # ─── Sysctl tuning for NAS workloads ────────────────────────────────────
  boot.kernel.sysctl = {
    # inotify — needed for file change monitoring with many files
    "fs.inotify.max_user_watches"   = 524288;
    "fs.inotify.max_user_instances" = 512;
    "fs.inotify.max_queued_events"  = 32768;

    # VM — reduce cache pressure, improve NAS throughput
    "vm.swappiness"          = 10;
    "vm.vfs_cache_pressure"  = 50;
    "vm.dirty_background_ratio" = 5;
    "vm.dirty_ratio"            = 15;

    # TCP — better throughput for SMB/NFS/rsync
    "net.core.rmem_max"               = 134217728;
    "net.core.wmem_max"               = 134217728;
    "net.ipv4.tcp_rmem"               = "4096 87380 67108864";
    "net.ipv4.tcp_wmem"               = "4096 65536 67108864";
    "net.ipv4.tcp_congestion_control" = "bbr";
  };

  # ─── Packages available system-wide ────────────────────────────────────
  environment.systemPackages = with pkgs; [
    vim
    htop
    git
    wget
    curl
    lsof
    iotop
    zfs
    smartmontools
    hdparm
    ipmitool
    pciutils
    usbutils
    nettools
    ethtool
    tcpdump
  ];

  # ─── State version ───────────────────────────────────────────────────────
  # Do NOT change this after initial install. It controls NixOS migration logic.
  system.stateVersion = "25.11";
}
